# https://taskfile.dev

version: "3"

tasks:
  local.dev:
    cmds:
      - >
        docker run --rm -p 4000:4000 --volume="$PWD:/site"
        --volume="$PWD/vendor/bundle:/usr/local/bundle"
        -it bretfisher/jekyll-serve:stable-20260315-2119a31 jekyll s --host=0.0.0.0 --force_polling
